/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualanbarang;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Eki-PC
 */
public class ViewItem extends javax.swing.JFrame {

    /**
     * Creates new form ViewItem
     */
    public ViewItem() {
        initComponents();
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemData_table = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        updateItem_btn = new javax.swing.JButton();
        deleteItem_btn = new javax.swing.JButton();
        createItem_btn = new javax.swing.JButton();
        createItem_btn1 = new javax.swing.JButton();
        exit_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("View");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Page");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Item");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(280, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 360, 720);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        itemData_table.setBackground(new java.awt.Color(204, 255, 255));
        itemData_table.setForeground(new java.awt.Color(51, 51, 51));
        itemData_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Price", "Stock", "Supplied By"
            }
        ));
        jScrollPane1.setViewportView(itemData_table);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Data Item");

        updateItem_btn.setBackground(new java.awt.Color(51, 51, 51));
        updateItem_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updateItem_btn.setForeground(new java.awt.Color(255, 255, 255));
        updateItem_btn.setText("Update Data");
        updateItem_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateItem_btnActionPerformed(evt);
            }
        });

        deleteItem_btn.setBackground(new java.awt.Color(51, 51, 51));
        deleteItem_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deleteItem_btn.setForeground(new java.awt.Color(255, 255, 255));
        deleteItem_btn.setText("Delete Data");
        deleteItem_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteItem_btnActionPerformed(evt);
            }
        });

        createItem_btn.setBackground(new java.awt.Color(51, 51, 51));
        createItem_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createItem_btn.setForeground(new java.awt.Color(255, 255, 255));
        createItem_btn.setText("Create Data");
        createItem_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createItem_btnActionPerformed(evt);
            }
        });

        createItem_btn1.setBackground(new java.awt.Color(51, 51, 51));
        createItem_btn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createItem_btn1.setForeground(new java.awt.Color(255, 255, 255));
        createItem_btn1.setText("Print Data");
        createItem_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createItem_btn1ActionPerformed(evt);
            }
        });

        exit_btn.setBackground(new java.awt.Color(51, 51, 51));
        exit_btn.setForeground(new java.awt.Color(255, 255, 255));
        exit_btn.setText("Exit");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exit_btn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(updateItem_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteItem_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createItem_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(createItem_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exit_btn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateItem_btn)
                    .addComponent(deleteItem_btn)
                    .addComponent(createItem_btn)
                    .addComponent(createItem_btn1))
                .addGap(57, 57, 57))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(360, 0, 720, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteItem_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteItem_btnActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps,ps2;
        ResultSet rs2;
        int row = itemData_table.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select the data you want to delete!");       
        }else{
            try {
                String value=(itemData_table.getModel().getValueAt(row, 0).toString());
                String query = "DELETE FROM `items` WHERE `id_barang`='"+value+"'";
                System.out.println(query);
                ps = MyConnection.getConnection().prepareStatement(query);
                ps.executeUpdate();
                DefaultTableModel tm = (DefaultTableModel)itemData_table.getModel();
                JOptionPane.showMessageDialog(null, "Barang berhasil dihapus");
                ViewItem view = new ViewItem();
                view.setVisible(true);
                view.pack();
                view.setLocationRelativeTo(null);
                view.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();

            } catch (SQLException ex) {
                Logger.getLogger(ViewItem.class.getName()).log(Level.SEVERE, null, ex);
            }        
        }
        
    }//GEN-LAST:event_deleteItem_btnActionPerformed

    private void updateItem_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateItem_btnActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps,ps2;
        ResultSet rs2;
        int row = itemData_table.getSelectedRow();
        if(row < 0){
            JOptionPane.showMessageDialog(null, "Please select the data you want to update!");
        }else{
            try {
                String idItem=(itemData_table.getModel().getValueAt(row, 0).toString());
                String name=(itemData_table.getModel().getValueAt(row, 1).toString());
                String price=(itemData_table.getModel().getValueAt(row, 2).toString());
                String stock=(itemData_table.getModel().getValueAt(row, 3).toString());
                String idSupplier=(itemData_table.getModel().getValueAt(row, 4).toString());
                String query = "UPDATE `items` SET `id_barang`='"+idItem+"', `namaBarang`='"+name+"', `hargaBarang`='"+price+"', `stockBarang`='"+stock+"', `id_supplier`='"+idSupplier+"' WHERE `id_barang`='"+idItem+"'";
                ps = MyConnection.getConnection().prepareStatement(query);
                ps.executeUpdate();
                DefaultTableModel tm = (DefaultTableModel)itemData_table.getModel();
                JOptionPane.showMessageDialog(null, "Barang berhasil diupdate");
                ViewItem view = new ViewItem();
                view.setVisible(true);
                view.pack();
                view.setLocationRelativeTo(null);
                view.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();

            } catch (SQLException ex) {
                Logger.getLogger(ViewItem.class.getName()).log(Level.SEVERE, null, ex);
            }        
        }
    }//GEN-LAST:event_updateItem_btnActionPerformed

    private void createItem_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createItem_btnActionPerformed
        // TODO add your handling code here:
                Item item = new Item();
                item.setVisible(true);
                item.pack();
                item.setLocationRelativeTo(null);
                item.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
    }//GEN-LAST:event_createItem_btnActionPerformed

    private void createItem_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createItem_btn1ActionPerformed
        // TODO add your handling code here:
        try {
            String file = "C:\\Users\\Eki-PC\\Documents\\NetBeansProjects\\PenjualanBarang\\src\\penjualanbarang\\DataItem.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(file);
            JasperPrint jp = JasperFillManager.fillReport(jr,null,MyConnection.getConnection());
            JasperViewer.viewReport(jp);
        } catch (JRException ex) {
            Logger.getLogger(ViewSupplier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_createItem_btn1ActionPerformed

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        home.pack();
        home.setLocationRelativeTo(null);
        home.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_exit_btnActionPerformed
    private void fillTable(){
        PreparedStatement ps,ps2;
        ResultSet rs,rs2;
        try {
            DefaultTableModel tm = (DefaultTableModel)itemData_table.getModel();                
            String query2 = "SELECT * FROM `items`";;
            ps2 = MyConnection.getConnection().prepareStatement(query2);
            rs2 = ps2.executeQuery();
            DefaultTableModel dm = (DefaultTableModel)itemData_table.getModel();
            while(rs2.next()){
                Object o[] ={rs2.getString("id_barang"),rs2.getString("namaBarang"),rs2.getString("hargaBarang"),rs2.getString("stockBarang"),rs2.getString("id_supplier")};
                dm.addRow(o);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ViewItem.class.getName()).log(Level.SEVERE, null, ex);    
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createItem_btn;
    private javax.swing.JButton createItem_btn1;
    private javax.swing.JButton deleteItem_btn;
    private javax.swing.JButton exit_btn;
    private javax.swing.JTable itemData_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateItem_btn;
    // End of variables declaration//GEN-END:variables
}
